/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.financio.view;

import java.awt.CardLayout;
import java.awt.Panel;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import pe.edu.utp.financio.dao.impl.CategoriaDaoImpl;
import pe.edu.utp.financio.dao.impl.MovimientoDaoImpl;

import pe.edu.utp.financio.dao1.MovimientoDAO;
import pe.edu.utp.financio.modelo.Categoria;
import pe.edu.utp.financio.modelo.Movimiento;
import pe.edu.utp.financio.modelo.Usuario;
import pe.edu.utp.financio.service.MovimientoService;
import pe.edu.utp.financio.service.impl.MovimientoServiceImpl;

/**
 *
 * @author User
 */
public class JframeInicio extends javax.swing.JFrame {

    /**
     * Creates new form JframeInicio
     */
    
    
    
    
    private Usuario usuario;
    CardLayout cardLayout;
    private MovimientoService movimientoService = new MovimientoServiceImpl();
    MovimientoDaoImpl daoMov = new MovimientoDaoImpl();
    
    
    



    private void cargarCategorias() throws SQLException {
        CategoriaDaoImpl dao = new CategoriaDaoImpl();
        List<Categoria> categoriasIngresos = dao.listarPorUsuario(usuario.getId(), "INGRESO");
        List<Categoria> categoriasGastos = dao.listarPorUsuario(usuario.getId(), "GASTO");

        cbxingrsocategoria.removeAllItems();
        cbxGastoCategoria.removeAllItems();



    // Llenar combos
    for (Categoria c : categoriasIngresos) {
        cbxingrsocategoria.addItem(c);
    }
    for (Categoria cg : categoriasGastos) {
        cbxGastoCategoria.addItem(cg);
    }

    // Depuración
    System.out.println("Categorías INGRESO en combo: " + categoriasIngresos.size());
    for (Categoria c : categoriasIngresos) {
        System.out.println(" -> " + c.getNombre());
    }

    System.out.println("Categorías GASTO en combo: " + categoriasGastos.size());
    for (Categoria cg : categoriasGastos) {
        System.out.println(" -> " + cg.getNombre());
        }
    }

    public JframeInicio(Usuario usuario) {
        initComponents();
        
        
        
        
        // Configurar columnas de la tabla de movimientos
        DefaultTableModel modeloMovimientos = new DefaultTableModel(
                new Object[]{"Fecha", "Tipo", "Categoría", "Descripción", "Monto"}, 0
        );
        tblMovimientos.setModel(modeloMovimientos);
        
        // Acción del botón Movimiento
    btnMovimiento.addActionListener(e -> {
        cardLayout.show(JPpanelcontenido, "panelMovimientos");
        cargarMovimientos(); // 👈 cargar datos en la tabla
    });


        this.usuario = usuario;

        JPpanelcontenido.setLayout(new CardLayout());
        cardLayout = (CardLayout) JPpanelcontenido.getLayout();

        JPpanelcontenido.add(Panelnicio, "panelInicio");
        JPpanelcontenido.add(PanelIngreso, "panelIngresos");
        JPpanelcontenido.add(PanelGastos, "panelGastos");
        JPpanelcontenido.add(PanelAnalisisFinanzas, "panelAnalisisFinanzas");
        JPpanelcontenido.add(PanelMovimientos, "panelMovimientos");
        JPpanelcontenido.add(PanelMetas, "panelMetas");
        JPpanelcontenido.add(PanelExportarDatos, "panelExportarDatos");

        btnInicio.addActionListener(e -> cardLayout.show(JPpanelcontenido, "panelInicio"));
        btnIngreso.addActionListener(e -> cardLayout.show(JPpanelcontenido, "panelIngresos"));
        btnGastos.addActionListener(e -> cardLayout.show(JPpanelcontenido, "panelGastos"));
        btnAnalisisFinanzas.addActionListener(e -> cardLayout.show(JPpanelcontenido, "panelAnalisisFinanzas"));
        btnMovimiento.addActionListener(e -> cardLayout.show(JPpanelcontenido, "panelMovimientos"));
        btnMetas.addActionListener(e -> cardLayout.show(JPpanelcontenido, "panelMetas"));
        btnExportarDatos.addActionListener(e -> cardLayout.show(JPpanelcontenido, "panelExportarDatos"));

        try {
            cargarCategorias();
            cargarIngresos();
            cargarGastos();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar categorías: " + ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPpanelMenu = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnIngreso = new javax.swing.JButton();
        btnGastos = new javax.swing.JButton();
        btnAnalisisFinanzas = new javax.swing.JButton();
        btnMovimiento = new javax.swing.JButton();
        btnMetas = new javax.swing.JButton();
        btnExportarDatos = new javax.swing.JButton();
        JPpanelcontenido = new javax.swing.JPanel();
        PanelIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtingresocantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtingresodescripcion = new javax.swing.JTextField();
        cbxingrsocategoria = new javax.swing.JComboBox<>();
        btningresoguardar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblIngreso = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        PanelGastos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGastoMonto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGastoDescripcion = new javax.swing.JTextField();
        cbxGastoCategoria = new javax.swing.JComboBox<>();
        btnGastoGuardar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();
        btnGastoAgrCategoria = new javax.swing.JButton();
        btnGastoEliminar = new javax.swing.JButton();
        PanelAnalisisFinanzas = new javax.swing.JPanel();
        PanelMovimientos = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        PanelMetas = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        PanelExportarDatos = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Panelnicio = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btncomenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPpanelMenu.setLayout(new java.awt.GridLayout(0, 1));

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        JPpanelMenu.add(btnInicio);

        btnIngreso.setText("Ingresos");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });
        JPpanelMenu.add(btnIngreso);

        btnGastos.setText("Gastos");
        btnGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastosActionPerformed(evt);
            }
        });
        JPpanelMenu.add(btnGastos);

        btnAnalisisFinanzas.setText("Análisis de finanzas");
        btnAnalisisFinanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisisFinanzasActionPerformed(evt);
            }
        });
        JPpanelMenu.add(btnAnalisisFinanzas);

        btnMovimiento.setText("Movimientos");
        btnMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientoActionPerformed(evt);
            }
        });
        JPpanelMenu.add(btnMovimiento);

        btnMetas.setText("Metas");
        JPpanelMenu.add(btnMetas);

        btnExportarDatos.setText("Exportar datos");
        btnExportarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarDatosActionPerformed(evt);
            }
        });
        JPpanelMenu.add(btnExportarDatos);

        JPpanelcontenido.setLayout(new java.awt.CardLayout());

        PanelIngreso.setBackground(new java.awt.Color(204, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("Nuevo Ingreso");

        jLabel2.setText("Monto:");

        txtingresocantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingresocantidadActionPerformed(evt);
            }
        });

        jLabel4.setText("Categoria:");

        jLabel5.setText("Descripción:");

        txtingresodescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingresodescripcionActionPerformed(evt);
            }
        });

        cbxingrsocategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxingrsocategoriaActionPerformed(evt);
            }
        });

        btningresoguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/financio/images/Guardar.png"))); // NOI18N
        btningresoguardar.setText("Guardar");
        btningresoguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresoguardarActionPerformed(evt);
            }
        });

        tblIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblIngreso);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/financio/images/Añadir.png"))); // NOI18N
        btnAgregar.setText("Agregar Categoria");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/financio/images/Eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresoLayout = new javax.swing.GroupLayout(PanelIngreso);
        PanelIngreso.setLayout(PanelIngresoLayout);
        PanelIngresoLayout.setHorizontalGroup(
            PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(PanelIngresoLayout.createSequentialGroup()
                        .addGroup(PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtingresocantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxingrsocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtingresodescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelIngresoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnAgregar)))
                        .addGap(50, 50, 50)
                        .addGroup(PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelIngresoLayout.createSequentialGroup()
                                .addComponent(btningresoguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        PanelIngresoLayout.setVerticalGroup(
            PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtingresocantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbxingrsocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtingresodescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(PanelIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btningresoguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        JPpanelcontenido.add(PanelIngreso, "card3");

        PanelGastos.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel6.setText("Nuevo Gasto");

        jLabel7.setText("Monto:");

        jLabel9.setText("Categoria:");

        jLabel10.setText("Descripción:");

        btnGastoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/financio/images/Guardar.png"))); // NOI18N
        btnGastoGuardar.setText("Guardar");
        btnGastoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastoGuardarActionPerformed(evt);
            }
        });

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblGastos);

        btnGastoAgrCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/financio/images/Añadir.png"))); // NOI18N
        btnGastoAgrCategoria.setText("Agregar Categoria");
        btnGastoAgrCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastoAgrCategoriaActionPerformed(evt);
            }
        });

        btnGastoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/financio/images/Eliminar.png"))); // NOI18N
        btnGastoEliminar.setText("Eliminar");
        btnGastoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastoEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGastosLayout = new javax.swing.GroupLayout(PanelGastos);
        PanelGastos.setLayout(PanelGastosLayout);
        PanelGastosLayout.setHorizontalGroup(
            PanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGastosLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGastosLayout.createSequentialGroup()
                        .addGroup(PanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(PanelGastosLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnGastoAgrCategoria)
                                .addGap(58, 58, 58)
                                .addComponent(btnGastoGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnGastoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelGastosLayout.createSequentialGroup()
                        .addGroup(PanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelGastosLayout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxGastoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGastoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGastoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 244, Short.MAX_VALUE))))
        );
        PanelGastosLayout.setVerticalGroup(
            PanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGastosLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGastosLayout.createSequentialGroup()
                        .addComponent(txtGastoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cbxGastoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtGastoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGastosLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE))
                    .addGroup(PanelGastosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGastoAgrCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGastoGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGastoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(157, 157, 157))
        );

        JPpanelcontenido.add(PanelGastos, "card4");

        PanelAnalisisFinanzas.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout PanelAnalisisFinanzasLayout = new javax.swing.GroupLayout(PanelAnalisisFinanzas);
        PanelAnalisisFinanzas.setLayout(PanelAnalisisFinanzasLayout);
        PanelAnalisisFinanzasLayout.setHorizontalGroup(
            PanelAnalisisFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        PanelAnalisisFinanzasLayout.setVerticalGroup(
            PanelAnalisisFinanzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        JPpanelcontenido.add(PanelAnalisisFinanzas, "card5");

        PanelMovimientos.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel11.setText("Movimientos");

        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Tipo", "Categoria", "Descripcion", "Monto"
            }
        ));
        jScrollPane1.setViewportView(tblMovimientos);

        jLabel12.setText("Filtrar:");

        jLabel13.setText("a");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Ingresos", "Egresos", " " }));

        jLabel14.setText("Tipo movimiento:");

        jLabel15.setText("Por Fecha:");

        jLabel16.setText("Tipo categoria");

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/financio/images/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar Filtros");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel15))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout PanelMovimientosLayout = new javax.swing.GroupLayout(PanelMovimientos);
        PanelMovimientos.setLayout(PanelMovimientosLayout);
        PanelMovimientosLayout.setHorizontalGroup(
            PanelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMovimientosLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel11)
                .addContainerGap(706, Short.MAX_VALUE))
            .addGroup(PanelMovimientosLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(PanelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelMovimientosLayout.setVerticalGroup(
            PanelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMovimientosLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        JPpanelcontenido.add(PanelMovimientos, "card6");

        jLabel17.setText("Metas:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Obetivo", "Progreso", "%Importe de ingresos"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Nombre:");

        jLabel19.setText("Objetivo:");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel20.setText("Fecha limite meta:");

        jLabel21.setText("% destinado:");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jButton6.setText("Crear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Crear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Eliminar");

        javax.swing.GroupLayout PanelMetasLayout = new javax.swing.GroupLayout(PanelMetas);
        PanelMetas.setLayout(PanelMetasLayout);
        PanelMetasLayout.setHorizontalGroup(
            PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMetasLayout.createSequentialGroup()
                .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMetasLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelMetasLayout.createSequentialGroup()
                                .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelMetasLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(PanelMetasLayout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(PanelMetasLayout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(42, 42, 42)
                                .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7)
                                    .addComponent(jButton8))
                                .addGap(249, 249, 249))))
                    .addGroup(PanelMetasLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMetasLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(403, Short.MAX_VALUE))
        );
        PanelMetasLayout.setVerticalGroup(
            PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMetasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addGap(6, 6, 6)
                .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        JPpanelcontenido.add(PanelMetas, "card7");

        jLabel22.setText("Exportar datos:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opciones", "Ingresos", "gatos ", "movimientos" }));

        jLabel23.setText("Desde fecha:");

        jLabel24.setText("a");

        jButton9.setText("Exportar a PDF");

        jButton10.setText("Exportar a xlsx");

        javax.swing.GroupLayout PanelExportarDatosLayout = new javax.swing.GroupLayout(PanelExportarDatos);
        PanelExportarDatos.setLayout(PanelExportarDatosLayout);
        PanelExportarDatosLayout.setHorizontalGroup(
            PanelExportarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(PanelExportarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                .addGroup(PanelExportarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(PanelExportarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addContainerGap(573, Short.MAX_VALUE))
        );
        PanelExportarDatosLayout.setVerticalGroup(
            PanelExportarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                .addGroup(PanelExportarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel22)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel23))
                    .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelExportarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelExportarDatosLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelExportarDatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        JPpanelcontenido.add(PanelExportarDatos, "card8");

        Panelnicio.setBackground(new java.awt.Color(204, 204, 255));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel25.setText("Bienvenido:");

        lblNombre.setText("\"Nombre \"");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel27.setText("Gestiona tus finanzas con financio ");

        jLabel28.setText("Controla los ingresos y gatos de manera sencilla");

        btncomenzar.setText("Comenzar");

        javax.swing.GroupLayout PanelnicioLayout = new javax.swing.GroupLayout(Panelnicio);
        Panelnicio.setLayout(PanelnicioLayout);
        PanelnicioLayout.setHorizontalGroup(
            PanelnicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelnicioLayout.createSequentialGroup()
                .addGroup(PanelnicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelnicioLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(PanelnicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelnicioLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelnicioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelnicioLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btncomenzar)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        PanelnicioLayout.setVerticalGroup(
            PanelnicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelnicioLayout.createSequentialGroup()
                .addGroup(PanelnicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelnicioLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel25))
                    .addGroup(PanelnicioLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel28)
                .addGap(81, 81, 81)
                .addComponent(btncomenzar)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        JPpanelcontenido.add(Panelnicio, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPpanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPpanelcontenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPpanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPpanelcontenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGastosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnExportarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarDatosActionPerformed

    private void btnMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovimientoActionPerformed

    private void btnAnalisisFinanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisisFinanzasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalisisFinanzasActionPerformed

    private void txtingresocantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingresocantidadActionPerformed

    }//GEN-LAST:event_txtingresocantidadActionPerformed

    private void cbxingrsocategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxingrsocategoriaActionPerformed

    }//GEN-LAST:event_cbxingrsocategoriaActionPerformed

    private void txtingresodescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingresodescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtingresodescripcionActionPerformed

    private void btningresoguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresoguardarActionPerformed

        try {
            BigDecimal monto = new BigDecimal(txtingresocantidad.getText().trim());
            String descripcion = txtingresodescripcion.getText().trim();

            // Obtenemos la categoría seleccionada
            Categoria seleccionada = (Categoria) cbxingrsocategoria.getSelectedItem();

            // Crear nueva categoría si seleccionó "➕ Nueva categoría..."
            if (seleccionada != null && seleccionada.getId() == -1) {
                String nuevaCat = JOptionPane.showInputDialog(this, "Nombre de la nueva categoría:");
                if (nuevaCat != null && !nuevaCat.trim().isEmpty()) {
                    CategoriaDaoImpl daoCat = new CategoriaDaoImpl();
                    int idNueva = daoCat.registrar(new Categoria(0, usuario.getId(), nuevaCat, "INGRESO"));
                    cargarCategorias(); // refresca el combo

                    // Seleccionamos la nueva categoría
                    for (int i = 0; i < cbxingrsocategoria.getItemCount(); i++) {
                        Categoria c = (Categoria) cbxingrsocategoria.getItemAt(i);
                        if (c.getId() == idNueva) {
                            cbxingrsocategoria.setSelectedIndex(i);
                            seleccionada = c;
                            break;
                        }
                    }
                    JOptionPane.showMessageDialog(this, "Categoría creada: " + nuevaCat);
                } else {
                    JOptionPane.showMessageDialog(this, "⚠️ No ingresaste un nombre válido para la categoría.");
                    return; // cancelar si no puso nada
                }
            }

            if (seleccionada == null || seleccionada.getId() <= 0) {
                JOptionPane.showMessageDialog(this, "⚠️ Selecciona una categoría válida.");
                return;
            }

            // Registramos el ingreso
            Movimiento m = new Movimiento();
            m.setIdUsuario(usuario.getId());
            m.setIdCategoria(seleccionada.getId());
            m.setMonto(monto);
            m.setCategoria(seleccionada.getNombre());
            m.setDescripcion(descripcion);

            MovimientoDaoImpl daoMov = new MovimientoDaoImpl();
            int idGenerado = daoMov.registrarmovimiento(m);

            if (idGenerado > 0) {
                JOptionPane.showMessageDialog(this, "✅ Ingreso registrado con ID: " + idGenerado);
                txtingresocantidad.setText("");
                txtingresodescripcion.setText("");

                //recargar la tabla desde la BD
                cargarIngresos();
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo registrar el ingreso");
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "⚠️ Monto no válido.");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "⚠️ Error: " + ex.getMessage());
        }


    }//GEN-LAST:event_btningresoguardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nuevaCat = JOptionPane.showInputDialog(this, "Nombre de la nueva Categoria:");
        if (nuevaCat != null && !nuevaCat.trim().isEmpty()) {
            try {
                CategoriaDaoImpl daoCat = new CategoriaDaoImpl();
                int idNueva = daoCat.registrar(new Categoria(0, usuario.getId(), nuevaCat, "INGRESO"));

                //refrescamos
                cargarCategorias();

                //seleccionamos automaticamente la nueva categoria creada
                for (int i = 0; i < cbxingrsocategoria.getItemCount(); i++) {
                    Categoria c = (Categoria) cbxingrsocategoria.getItemAt(i);
                    if (c.getId() == idNueva) {
                        cbxingrsocategoria.setSelectedIndex(i);
                        break;
                    }
                }
                JOptionPane.showMessageDialog(this, "Categoria creada: " + nuevaCat);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al crear categoria: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "No ingresaste un nombre valido.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int fila = tblIngreso.getSelectedRow();

        if (fila >= 0) {
            // ID está en la primera columna
            int id = Integer.parseInt(tblIngreso.getValueAt(fila, 0).toString());

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que deseas eliminar el ingreso con ID " + id + "?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                try {

                    int filasEliminadas = daoMov.eliminarMovimiento(id);

                    if (filasEliminadas > 0) {
                        JOptionPane.showMessageDialog(this, "✅ Ingreso eliminado correctamente.");
                        cargarIngresos(); // 👈 refresca toda la tabla
                    } else {
                        JOptionPane.showMessageDialog(this, "⚠️ No se encontró el ingreso con ID: " + id);
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "⚠️ Error al eliminar: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "⚠️ Selecciona un ingreso primero.");
        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGastoAgrCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastoAgrCategoriaActionPerformed
        String nuevaCat = JOptionPane.showInputDialog(this, "Nombre de la nueva Categoria:");
        if (nuevaCat != null && !nuevaCat.trim().isEmpty()) {
            try {
                CategoriaDaoImpl daoCat = new CategoriaDaoImpl();
                int idNueva = daoCat.registrar(new Categoria(0, usuario.getId(), nuevaCat, "GASTO"));

                //refrescamos
                cargarCategorias();

                //seleccionamos automaticamente la nueva categoria creada
                for (int i = 0; i < cbxGastoCategoria.getItemCount(); i++) {
                    Categoria c = (Categoria) cbxGastoCategoria.getItemAt(i);
                    if (c.getId() == idNueva) {
                        cbxGastoCategoria.setSelectedIndex(i);
                        break;
                    }
                }
                JOptionPane.showMessageDialog(this, "Categoria creada: " + nuevaCat);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al crear categoria: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "No ingresaste un nombre valido.");
        }
    }//GEN-LAST:event_btnGastoAgrCategoriaActionPerformed

    private void btnGastoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastoEliminarActionPerformed
        int fila = tblGastos.getSelectedRow();

        if (fila >= 0) {
            // ID está en la primera columna
            int id = Integer.parseInt(tblGastos.getValueAt(fila, 0).toString());

            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "¿Seguro que deseas eliminar el ingreso con ID " + id + "?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm == JOptionPane.YES_OPTION) {
                try {

                    int filasEliminadas = daoMov.eliminarMovimiento(id);

                    if (filasEliminadas > 0) {
                        JOptionPane.showMessageDialog(this, "✅ Ingreso eliminado correctamente.");
                        cargarGastos(); // 👈 refresca toda la tabla
                    } else {
                        JOptionPane.showMessageDialog(this, "⚠️ No se encontró el ingreso con ID: " + id);
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "⚠️ Error al eliminar: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "⚠️ Selecciona un ingreso primero.");
        }

    }//GEN-LAST:event_btnGastoEliminarActionPerformed

    private void btnGastoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastoGuardarActionPerformed
        try {
            BigDecimal monto = new BigDecimal(txtGastoMonto.getText().trim());
            String descripcion = txtGastoDescripcion.getText().trim();

            // Obtenemos la categoría seleccionada
            Categoria seleccionada = (Categoria) cbxGastoCategoria.getSelectedItem();

            // Crear nueva categoría si seleccionó "➕ Nueva categoría..."
            if (seleccionada != null && seleccionada.getId() == -1) {
                String nuevaCat = JOptionPane.showInputDialog(this, "Nombre de la nueva categoría:");
                if (nuevaCat != null && !nuevaCat.trim().isEmpty()) {
                    CategoriaDaoImpl daoCat = new CategoriaDaoImpl();
                    int idNueva = daoCat.registrar(new Categoria(0, usuario.getId(), nuevaCat, "GASTO"));
                    cargarCategorias(); // refresca el combo

                    // Seleccionamos la nueva categoría
                    for (int i = 0; i < cbxGastoCategoria.getItemCount(); i++) {
                        Categoria c = (Categoria) cbxGastoCategoria.getItemAt(i);
                        if (c.getId() == idNueva) {
                            cbxGastoCategoria.setSelectedIndex(i);
                            seleccionada = c;
                            break;
                        }
                    }
                    JOptionPane.showMessageDialog(this, "Categoría creada: " + nuevaCat);
                } else {
                    JOptionPane.showMessageDialog(this, "⚠️ No ingresaste un nombre válido para la categoría.");
                    return; // cancelar si no puso nada
                }
            }

            if (seleccionada == null || seleccionada.getId() <= 0) {
                JOptionPane.showMessageDialog(this, "⚠️ Selecciona una categoría válida.");
                return;
            }

            // Registramos el ingreso
            Movimiento m = new Movimiento();
            m.setIdUsuario(usuario.getId());
            m.setIdCategoria(seleccionada.getId());
            m.setMonto(monto);
            m.setCategoria(seleccionada.getNombre());
            m.setDescripcion(descripcion);

            MovimientoDaoImpl daoMov = new MovimientoDaoImpl();
            int idGenerado = daoMov.registrarmovimiento(m);

            if (idGenerado > 0) {
                JOptionPane.showMessageDialog(this, "✅ Ingreso registrado con ID: " + idGenerado);
                txtGastoMonto.setText("");
                txtGastoDescripcion.setText("");

                //recargar la tabla desde la BD
                cargarGastos();
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo registrar el ingreso");
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "⚠️ Monto no válido.");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "⚠️ Error: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnGastoGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       cargarMovimientos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarIngresos() {
        try {
            //obtener el modelo de la tabla
            DefaultTableModel modelo = (DefaultTableModel) tblIngreso.getModel();
            modelo.setRowCount(0); //limpiar filas previas

            //obtener lista desde la BD
            List<Movimiento> lista = daoMov.listarIngresosPorUsuario(usuario.getId());

            //agregar cada ingreso a la tabla
            for (Movimiento m : lista) {
                modelo.addRow(new Object[]{
                    m.getId(),
                    m.getCategoria(),
                    m.getDescripcion(),
                    m.getMonto()
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "⚠ Error al cargar ingresos: " + ex.getMessage());
        }
    }

    private void cargarGastos() {
        try {
            //obtener el modelo de la tabla
            DefaultTableModel modelo = (DefaultTableModel) tblGastos.getModel();
            modelo.setRowCount(0); //limpiar filas previas

            //obtener lista desde la BD
            List<Movimiento> lista = daoMov.listarGastosPorUsuario(usuario.getId());

            //agregar cada ingreso a la tabla
            for (Movimiento m : lista) {
                modelo.addRow(new Object[]{
                    m.getId(),
                    m.getCategoria(),
                    m.getDescripcion(),
                    m.getMonto()
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "⚠ Error al cargar ingresos: " + ex.getMessage());
        }
    }
    
    /*private void cargarMovimientos() {
    try {
        DefaultTableModel modelo = (DefaultTableModel) tblMovimientos.getModel();
        modelo.setRowCount(0); // limpiar filas previas

        String opcion = (String) cbxTipo.getSelectedItem(); 
        List<Movimiento> lista;

        if ("Ingresos".equals(opcion)) {
            lista = movimientoService.listarIngresosPorUsuario(usuario.getId());
        } else if ("Egreso".equals(opcion)) {
            lista = movimientoService.listarGastosPorUsuario(usuario.getId());
        } else {
            lista = movimientoService.listarPorUsuario(usuario.getId());
        }

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

        for (Movimiento m : lista) {
            String fechaFormateada = m.getFecha().toLocalDateTime().format(formatter);

            modelo.addRow(new Object[]{
                fechaFormateada,
                m.getTipo(),
                m.getCategoria(),
                m.getDescripcion(),
                m.getMonto()
            });
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "⚠ Error al cargar movimientos: " + ex.getMessage());
    }
}*/
    /*private void cargarMovimientos() {
    try {
        DefaultTableModel modelo = (DefaultTableModel) tblMovimientos.getModel();
        modelo.setRowCount(0); // limpiar filas previas

        // Leer opción del ComboBox
        String opcion = (String) cbxTipo.getSelectedItem(); 
        List<Movimiento> lista;

        if ("Ingresos".equals(opcion)) {
            lista = movimientoService.listarIngresosPorUsuario(usuario.getId());
        } else if ("Egresos".equals(opcion)) {
            lista = movimientoService.listarGastosPorUsuario(usuario.getId());
        } else { // "Todos"
            lista = movimientoService.listarPorUsuario(usuario.getId());
        }

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

        for (Movimiento m : lista) {
            String fechaFormateada = m.getFecha().toLocalDateTime().format(formatter);

            modelo.addRow(new Object[]{
                fechaFormateada,
                m.getTipo(),
                m.getCategoria(),
                m.getDescripcion(),
                m.getMonto()
            });
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "⚠ Error al cargar movimientos: " + ex.getMessage());
    }
}*/
    
    private void cargarMovimientos() {
    try {
        DefaultTableModel modelo = (DefaultTableModel) tblMovimientos.getModel();
        modelo.setRowCount(0); // limpiar filas previas

        // Obtenemos valores seleccionados de los combos
        String opcionTipo = (String) cbxTipo.getSelectedItem();
        String opcionCategoria = (String) cbxCategoria.getSelectedItem();

        List<Movimiento> lista;

        // Filtrado por tipo
        if ("Ingresos".equals(opcionTipo)) {
            lista = movimientoService.listarIngresosPorUsuario(usuario.getId());
        } else if ("Egresos".equals(opcionTipo)) {
            lista = movimientoService.listarGastosPorUsuario(usuario.getId());
        } else {
            lista = movimientoService.listarPorUsuario(usuario.getId()); // Todos
        }

        // Filtrado adicional por categoría (si no es "Todas")
        if (opcionCategoria != null && !"Todas".equals(opcionCategoria)) {
            lista = lista.stream()
                         .filter(m -> opcionCategoria.equalsIgnoreCase(m.getCategoria()))
                         .toList();
        }

        // Formato de fecha sin segundos
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

        for (Movimiento m : lista) {
            String fechaFormateada = m.getFecha().toLocalDateTime().format(formatter);

            modelo.addRow(new Object[]{
                fechaFormateada,
                m.getTipo(),
                m.getCategoria(),
                m.getDescripcion(),
                m.getMonto()
            });
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "⚠ Error al cargar movimientos: " + ex.getMessage());
    }
}

    




    
 
   


    /**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPpanelMenu;
    private javax.swing.JPanel JPpanelcontenido;
    private javax.swing.JPanel PanelAnalisisFinanzas;
    private javax.swing.JPanel PanelExportarDatos;
    private javax.swing.JPanel PanelGastos;
    private javax.swing.JPanel PanelIngreso;
    private javax.swing.JPanel PanelMetas;
    private javax.swing.JPanel PanelMovimientos;
    private javax.swing.JPanel Panelnicio;
    private javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnAnalisisFinanzas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnExportarDatos;
    private javax.swing.JButton btnGastoAgrCategoria;
    private javax.swing.JButton btnGastoEliminar;
    private javax.swing.JButton btnGastoGuardar;
    public javax.swing.JButton btnGastos;
    public javax.swing.JButton btnIngreso;
    public javax.swing.JButton btnInicio;
    public javax.swing.JButton btnMetas;
    public javax.swing.JButton btnMovimiento;
    private javax.swing.JButton btncomenzar;
    private javax.swing.JButton btningresoguardar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<Categoria> cbxGastoCategoria;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JComboBox<Categoria> cbxingrsocategoria;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTable tblIngreso;
    private javax.swing.JTable tblMovimientos;
    private javax.swing.JTextField txtGastoDescripcion;
    private javax.swing.JTextField txtGastoMonto;
    private javax.swing.JTextField txtingresocantidad;
    private javax.swing.JTextField txtingresodescripcion;
    // End of variables declaration//GEN-END:variables
}
